src/components/DealProposalForm.tsx, src/components/buttons/ProviderButton.tsx, src/components/form/ValidatedInput.tsx, src/pages/Download.tsx
=> fix: linter

src/App.tsx, src/GlobalCtx.tsx, src/GlobalCtxProvider.tsx, src/components/DealProposalForm.tsx, src/components/ProviderSelector.tsx, src/pages/DealPreparation.tsx
It fetches:
- MinDealDuration
- MaxProveCommit
- Current block
from chain and makes the form easier when the chain is long running.
https://github.com/user-attachments/assets/f863cd29-f1a2-46bc-8618-969df95671c5
Closes #21.
=> feat: make form parameters runtime dependant

flake.nix, src/lib/p2p/bootstrapRequestResponse.ts, src/lib/p2p/index.ts, src/lib/p2p/servicesRequestResponse.ts, src/lib/sign.ts, src/pages/DealPreparation.tsx
=> feat: add support for upload to multiple SPs

src/GlobalCtx.tsx, src/GlobalCtxProvider.tsx, src/components/DealProposalForm.tsx, src/lib/consts.ts, src/pages/DealPreparation.tsx
=> feat: add real time to start/end block

src/GlobalCtx.tsx, src/GlobalCtxProvider.tsx, src/lib/jsonRpc.ts, src/pages/DealPreparation.tsx
The Delia counterpart to https://github.com/eigerco/polka-storage/pull/825
=> feat: add support for the extra ws API

src/components/DealProposalForm.tsx, src/components/FileUploader.tsx
Small improvement that (IMO) makes the UI much more pleasant
https://github.com/user-attachments/assets/698efda1-b2e5-4068-b190-2dd14c73385d
=> fix: make file drop smaller & move it up

src/pages/Download.tsx
https://github.com/user-attachments/assets/82cd94e6-956a-4422-96fa-59b3bd39689f
=> feat: add support for multiple SP addrs on retrieval

src/lib/timeout.ts, src/pages/Download.tsx
Requires #31 to be merged first
=> feat: add download timeout

src/lib/download.ts, src/lib/jsonRpc.ts, src/pages/DealPreparation.tsx, src/pages/Download.tsx
Downloads the submitted deal information upon completion. This will make retrieval much easier
Closes #45 
https://github.com/user-attachments/assets/189d77a0-3092-44c4-8e7d-0defe8128032
=> feat: download deal information on completion

.github/workflows/ci.yml, .github/workflows/deploy.yml, package.json, src/main.tsx, vite.config.ts
Available for test here: https://jmg-duarte.github.io/delia/
=> ci: add linting and GH Pages

README.md
=> docs: add qa on encryption

src/lib/p2p/bootstrapRequestResponse.ts, src/lib/resolvePeerIdMultiaddr.ts, src/pages/Download.tsx
Not performant but the alternative is slightly less readable and this just loops over small amounts of data
=> fix: consider wss when filtering providers

.husky/pre-commit, DEVELOPMENT.md, package.json, pnpm-lock.yaml
I was tired of failing CI, this should help
=> chore: add pre-commit setup

src/lib/fileUpload.ts, src/lib/jsonRpc.ts, src/lib/p2p/servicesRequestResponse.ts, src/pages/DealPreparation.tsx
=> fix: make delia work with public ips

src/lib/retrieval.ts
There was a race condition of sorts, using the array is better
=> fix: remove Promise.all from dialing

src/components/deal-proposal-form/DealProposalForm.tsx, src/components/deal-proposal-form/DurationInput.tsx
=> fix: duration validation

src/lib/retrieval.ts, src/pages/FileRetrieval.tsx
Reintroducing the check for retrieval providers availability
=> fix: return an error if retrieval providers not accessible

src/components/Toaster.tsx
https://github.com/user-attachments/assets/b9466e02-0867-46a0-a22f-6280c0c33127
=> fix: top center toast & larger text

src/components/ConnectWallet.tsx
=> fix: rework extension error

src/components/Balance.tsx, src/components/account/BalancePanel.tsx, src/pages/Account.tsx
=> feat: add free market balance and tooltips

src/App.tsx, src/components/account/BalancePanel.tsx, src/components/account/FaucetPanel.tsx, src/components/account/MarketDeposit.tsx, src/components/account/MarketWithdrawal.tsx, src/components/buttons/Button.tsx, src/components/buttons/RefreshButton.tsx, src/components/deal-proposal-form/DealProposalForm.tsx, src/pages/FileRetrieval.tsx
Unify buttons behaviour and style
=> fix: unify buttons

src/lib/dealProposal.ts, src/lib/jsonRpc.ts, src/lib/registry.ts, src/pages/DealPreparation.tsx
Remove the custom collateral calculation from the frontend
=> feat: remove collateral calculation from the frontend

src/lib/registry.ts
https://github.com/eigerco/polka-storage/pull/880 MUST be merged before
=> feat: use BlockNumber instead of u64

src/components/deal-proposal-form/DealProposalForm.tsx, src/components/deal-proposal-form/ProviderSelector.tsx, src/components/retrieval/DealStatus.tsx, src/lib/fileUpload.ts, src/lib/jsonRpc.ts, src/pages/Account.tsx, src/pages/DealPreparation.tsx
Pair to https://github.com/eigerco/polka-storage/pull/899
=> fix: move propose_deal from rpc to http
